services:
  postgres:
    image: postgres:17
    container_name: postgres_brfss_2022
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brfss_2022
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./data:/docker-entrypoint-initdb.d # Mount the local data folder for init
volumes:
  postgres_data: