services:
  postgres:
    image: postgres:17
    container_name: postgres_brfss_2023
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: chummy
      POSTGRES_DB: brfss_2023
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./data:/docker-entrypoint-initdb.d # Mount the local data folder for init
volumes:
  postgres_data: